baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
[params]
title = "I'm Arshad Hussain"
author = "unibik"
description = "Arshad Jane"
profilePicture = "images/profile.jpg"
