baseURL = 'https://unibik.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
profilePicture = "images/profile_pic.jpg"
